database:
  baseurl: "http://127.0.0.1:5000"
url:
  acmurl: "http://127.0.0.1:8084/acm/searchall/"
  bkurl: "http://127.0.0.1:8085/acms/"
mail:
  server: "smtp.gmail.com"
  port: 587
  ssl: False
  tls: True
  username: "oneyesexplora19@gmail.com"
  password: "admin@1yes"