database:
  baseurl: "http://127.0.0.1:8090"
accomodation:
  url: http://127.0.0.1:8084/acm/op
mail:
  server: "smtp.gmail.com"
  port: 587
  ssl: False
  tls: True
  username: "oneyesexplora19@gmail.com"
  password: "admin@1yes"